---
- name: Install remote facts
  hosts: all
  vars_files:
  - lab-vars/facts-vars.yaml
  tasks:
    - name: create remote directory
      file:
        state: directory
        recurse: yes
        path: "{{ remote_dir }}"
    - name: install new facts
      copy:
        src: "{{ facts_file }}"
        dest: "{{ remote_dir }}"
