---
- name: lab6 install and run mariadb database only on RHEL8 hosts; only set root password where mariadb was successfully started
  vars:
    distros:
    - "RedHat"
    - "CentOS"
  hosts: mysql
  tasks:
  - name: install and run packages
    block:
    - name: install pakacges
      package:
        name: "{{ mysql_packages }}"
        state: present
    - name: start services
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop: "{{ mysql_services }}"
      notify: set mysql root password
    when:
    - ansible_facts.distribution in distros
    - ansible_facts.distribution_major_version == "8"
  handlers:
  - name: set mysql root password for the server
    mysql_user:
      user: root
      password: "{{ mysql_root_password }}"
    listen: set mysql root password
  - name: create password drop file as recommended in the module
    template:
      src: templates/my-cnf.j2
      dest: /root/.my.cnf
      mode: '0600'
    listen: set mysql root password
...
